version: "2"

services:
  bt-panel:
    image: hk0828/bt-panel:debian
    ports:
      - "20:20"
      - "21:21"
      - "22:22"
      - "80:80"
      - "443:443"
      - "888:888"
      - "8888:8888"
    volumes:
- "./www:/www"